// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xend.Data;

#nullable disable

namespace Xend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230609080700_SeedClients")]
    partial class SeedClients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Xend.Models.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = "1",
                            Email = "john.doe@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            ClientId = "2",
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            ClientId = "3",
                            Email = "mike.johnson@example.com",
                            Name = "Mike Johnson"
                        },
                        new
                        {
                            ClientId = "4",
                            Email = "sarah.williams@example.com",
                            Name = "Sarah Williams"
                        },
                        new
                        {
                            ClientId = "5",
                            Email = "robert.brown@example.com",
                            Name = "Robert Brown"
                        },
                        new
                        {
                            ClientId = "6",
                            Email = "emily.davis@example.com",
                            Name = "Emily Davis"
                        },
                        new
                        {
                            ClientId = "7",
                            Email = "david.wilson@example.com",
                            Name = "David Wilson"
                        },
                        new
                        {
                            ClientId = "8",
                            Email = "jennifer.taylor@example.com",
                            Name = "Jennifer Taylor"
                        },
                        new
                        {
                            ClientId = "9",
                            Email = "michael.anderson@example.com",
                            Name = "Michael Anderson"
                        },
                        new
                        {
                            ClientId = "10",
                            Email = "jessica.clark@example.com",
                            Name = "Jessica Clark"
                        });
                });

            modelBuilder.Entity("Xend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Xend.Models.Transaction", b =>
                {
                    b.HasOne("Xend.Models.Client", "Client")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Xend.Models.Client", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
